language: ruby
cache: bundler
rvm:
- 2.1.0
sudo: false
deploy:
  edge:
    source: criteo-forks/dpl
    branch: chef_supermarket_dependency_on_mime_type
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Programming Languages
  client_key: ".travis/client.pem"
  on:
    tags: true
    all_branches: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_b5c5332c466c_key -iv $encrypted_b5c5332c466c_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
