language: ruby
cache: bundler
rvm:
- 2.3.0
sudo: false
deploy:
  edge: true
  skip_cleanup: true
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Programming Languages
  client_key: ".travis/client.pem"
  on:
    tags: true
    all_branches: false
before_deploy:
- openssl aes-256-cbc -K $encrypted_b5c5332c466c_key -iv $encrypted_b5c5332c466c_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
